test:
  adapter: postgresql
  host: localhost
  port: 5432
  database: notifiable-test
  username: matt
  password: 
  
development:
  adapter: postgresql
  host: localhost
  port: 5432
  database: notifiable-development
  username: matt
  password:


