source 'https://rubygems.org'
source 'https://rails-assets.org'

ruby "2.1.5"

# Core
gem 'rails', '4.1.8'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'quiet_assets', '~> 1.0.3'
gem 'pg', '~> 0.18.2'

# UI
gem 'rails-assets-bootstrap', '~> 3.3.2'
gem 'rails-assets-eonasdan-bootstrap-datetimepicker', '~> 4.0.0'
gem 'simple_form', '~> 3.1.0'

# Dashboard
gem 'chartkick', '~> 1.3.2'
gem 'rails-assets-highcharts', '4.1.1'
gem 'rails-assets-jquery.appear.js'
gem 'dateslices', '~> 0.0.3'

# Authentication
gem 'devise', '~> 3.4.1'
gem 'cancancan', '~> 1.9.2'
gem 'api-auth', '~> 1.1.0'

# Push Notifications
gem 'notifiable_admin', :path => "../.."
gem 'notifiable-rails', '~> 0.21.1'
gem 'notifiable-apns-grocer', '~> 0.11.0'
gem 'notifiable-gcm-spacialdb', '~> 0.7.0'
gem 'notifiable-mpns-nverinaud', '~> 0.6.0'

# Background processing
gem 'delayed_job_active_record', '~> 4.0.0'

# Pagination
gem "kaminari", "~> 0.15.1"
gem "bootstrap-kaminari-views", "~> 0.0.3"

# Seeding
gem 'faker'

group :development, :test do
  gem 'sqlite3'
  gem 'byebug'
  gem 'spring'
  gem 'spring-commands-rspec', '~> 1.0.4'
  gem 'guard', '~> 2.10.5'
  gem 'guard-rspec', '~> 4.5.0'
  gem 'thor'
end

group :test do
  gem 'rspec-rails', '~> 3.0.2'
  gem 'rspec-html-matchers', '~> 0.6.1'
  gem 'rspec-mocks', '~> 3.0.4'
  gem 'rspec_api_documentation', '~> 4.1.0'
  gem 'capybara', '~> 2.4.1'
  gem 'factory_girl_rails', '~> 4.4.1'
  gem "database_cleaner", "~> 1.2.0"
  gem 'simplecov', '~> 0.8.2'
  gem "simplecov-rcov", "~> 0.2.3"
  gem "json_spec", "~> 1.1.1"
  gem "brakeman"
  gem "launchy", "~> 2.4.2"
end