# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

TestApp::Application.load_tasks

desc "reset the database"
namespace :db do
  task :reset => [:environment, "db:drop", "db:create", "db:migrate"]    
end